### ISSUE TITLE
Recommended active accounts to follow

### ISSUE THREAD

**Issue by azzamsa** [nrc/rustaceans.org#524]
Hi.

Do you consider adding 'Recommended active accounts to follow' like [this](https://github.com/akullpp/awesome-java#twitter). 

It's nice to have this 'recommended'/'editor choice' list for new comers that don't even know anyone in rust community. But the downside is : what is the parameters for account to be considered 'recommended'.

Thanks in advance :)

**Comment by azzamsa** [comment]
I think some of them already mentioned [here](https://github.com/ctjhoa/rust-learning#fearless-rust-bloggers)

**Comment by nrc** [comment]
I don't think we should, primarily because deciding on who to recommend would be fraught. rustaceans is primarily intended as a directory - the idea is to answer the question "I found this person on GItHub, how can I get in touch with them on irc" or similar. Rather than support social network features or discoverability.
